GET  http://127.0.0.1:8000/api/usuario

### guardar
POST http://127.0.0.1:8000/api/usuario
Accept: application/json
Content-Type: application/json

{

    "name": "juan__prueba",
    "email": "juan__prueba@mail.com",
    "password": "juan123456"

}

### mostrar
GET  http://127.0.0.1:8000/api/usuario/2
Accept: application/json

### modificar
PUT   http://127.0.0.1:8000/api/usuario/3
Accept: application/json
Content-Type: application/json

{

    "name": "Nueva Ana Modificado",
    "email": "ana@mail.com",
    "password": "ana123456"

}
### eliminar
DELETE http://127.0.0.1:8000/api/usuario/2
